---
title: "Compare Linear and Cubist Modell"
author: "Aaron"
date: "7/12/2018"
output:
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
library(here)
library(tidyverse)
library(recipes)
library(rsample)
library(Cubist)
library(pander)

source(here("scripts", "00functions.R"))
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
knitr::read_chunk(here("scripts", "01load.R"))
knitr::read_chunk(here("scripts", "02preprocess.R"))
knitr::read_chunk(here("scripts", "03cubist-rules.R"))
knitr::read_chunk(here("scripts", "03linear-model.R"))
```

# Preparation

```{r preparation, child = here("documents", "preparation.Rmd")}
```

# Fit with Profession

```{r recipe-with-profession}
```

```{r cubist-rules}
```

```{r linear-model}
```

```{r}
fits <- as.data.frame(cbind(summary(data_cv$r2_cubist),
summary(data_cv$r2_lm), summary(data_cv$rmse_cubist),
summary(data_cv$rmse_lm)))
names(fits) <- c("R2 Cubist", "R2 Linear Model", "RMSE Cubist", "RMSE Linear Model")
pander(fits)
```

```{r}
ggplot(data_cv, aes(rmse_cubist)) + geom_density() + theme_minimal()
ggplot(data_cv, aes(id, rmse_cubist)) + geom_boxplot() + theme_minimal()

ggplot(data_cv, aes(r2_cubist)) + geom_density() + theme_minimal()
ggplot(data_cv, aes(id, r2_cubist)) + geom_boxplot() + theme_minimal()

ggplot(data_cv, aes(rmse_lm)) + geom_density() + theme_minimal()
ggplot(data_cv, aes(id, rmse_cubist)) + geom_boxplot() + theme_minimal()

ggplot(data_cv, aes(r2_lm)) + geom_density() + theme_minimal()
ggplot(data_cv, aes(id, r2_lm)) + geom_boxplot() + theme_minimal()
```

```{r}
data_cv_with <- data_cv
```

# Fit without Profession

```{r recipe-without-profession}
```

```{r cubist-rules}
```

```{r linear-model}
```

```{r}
fits <- as.data.frame(cbind(summary(data_cv$r2_cubist),
summary(data_cv$r2_lm), summary(data_cv$rmse_cubist),
summary(data_cv$rmse_lm)))
names(fits) <- c("R2 Cubist", "R2 Linear Model", "RMSE Cubist", "RMSE Linear Model")
pander(fits)
```

```{r}
ggplot(data_cv, aes(rmse_cubist)) + geom_density() + theme_minimal()
ggplot(data_cv, aes(id, rmse_cubist)) + geom_boxplot() + theme_minimal()

ggplot(data_cv, aes(r2_cubist)) + geom_density() + theme_minimal()
ggplot(data_cv, aes(id, r2_cubist)) + geom_boxplot() + theme_minimal()

ggplot(data_cv, aes(rmse_lm)) + geom_density() + theme_minimal()
ggplot(data_cv, aes(id, rmse_cubist)) + geom_boxplot() + theme_minimal()

ggplot(data_cv, aes(r2_lm)) + geom_density() + theme_minimal()
ggplot(data_cv, aes(id, r2_lm)) + geom_boxplot() + theme_minimal()
```
