---
title: "Is there a Difference if we ignore Profession?"
author: "Aaron"
date: "02/09/2018"
output:
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_float: yes
---
  
```{r setup, include=FALSE}
library(here)
library(tidyverse)
library(recipes)
library(rsample)
library(rpartScore)
library(pander)
library(rpart.plot)
library(tidyposterior)
library(DescTools)

source(here("scripts", "00functions.R"))
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = FALSE)
knitr::opts_chunk$set(cache.lazy = FALSE)
knitr::read_chunk(here("scripts", "01load.R"))
knitr::read_chunk(here("scripts", "02preprocess.R"))
knitr::read_chunk(here("scripts", "03rpart.R"))
knitr::read_chunk(here("scripts", "04measures.R"))
knitr::read_chunk(here("scripts", "05posterior.R"))
```

# Preparing

```{r load}
```

```{r predictors}
```

```{r resample}
```

```{r recipe}
```

```{r cache}
refit_rpart <- !fs::file_exists(here("out", "data_cv.rds"))
```

# Fit Model & Cross Validate

```{r rpart, eval = refit_rpart}
```

```{r cache2, eval = !refit_rpart}
data_cv <- read_rds(here("out", "data_cv.rds"))
```

```{r prediction}
```

```{r accuracy}
```

```{r cramerv}
```

# Refit Model to Full Datset

```{r}
fit_rpart <- function(recipe, ...){
  #browser()
  pred <- recipe %>% juice(all_predictors()) %>% names()
  out <- recipe %>% juice(all_outcomes()) %>% names()
  model_formula <- as.formula(paste0(out, " ~ ", paste(pred, collapse = " + ")))
  rpartScore(model_formula,
        data = juice(recipe, everything(), composition = "data.frame"),
        ...)
}
```

```{r, cache=TRUE}
recipe_i %>%
  prep(data, retain = TRUE) %>%
  fit_rpart(model = TRUE,
            split = "abs",
            prune = "mr") %>% 
  rpart.plot(fallen.leaves = F)
```

```{r, cache=TRUE}
recipe_e %>%
  prep(data, retain = TRUE) %>%
  fit_rpart(model = TRUE,
            split = "abs",
            prune = "mr") %>% 
  rpart.plot(fallen.leaves = F)
```

# Posterior Distribution for Difference in Accuracy

```{r acc-model, results='hide'}
```

```{r}
acc_stacked %>% 
  unite(id, id, id2) %>% 
  ggplot(aes(x = model, y = statistic, group = id, col = id)) + 
  geom_line(alpha = .75) + 
  theme_minimal() +
  theme(legend.position = "none") +
  NULL
acc_model$stan
summary(acc_vs) %>%
  select(contrast, probability, mean, lower, upper) %>%
  pander()
ggplot(acc_vs) + theme_minimal()
```

# Posterior Distribution for Difference in Cramer's V

```{r cramerv-model, results='hide'}
```

```{r}
cramerv_stacked %>% 
  unite(id, id, id2) %>% 
  ggplot(aes(x = model, y = statistic, group = id, col = id)) + 
  geom_line(alpha = .75) + 
  theme_minimal() +
  theme(legend.position = "none") +
  NULL
cramerv_model$stan
summary(cramerv_vs) %>%
  select(contrast, probability, mean, lower, upper) %>%
  pander()
ggplot(acc_vs) + theme_minimal()
```
