---
title: "Compare Linear and SVM with radial Kernal"
author: "Aaron"
date: "7/12/2018"
output:
  html_document:
  code_folding: hide
number_sections: yes
toc: yes
toc_float: yes
---
  
```{r setup, include=FALSE}
library(here)
library(tidyverse)
library(recipes)
library(rsample)
library(e1071)
library(pander)

source(here("scripts", "00functions.R"))
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
knitr::read_chunk(here("scripts", "01load.R"))
knitr::read_chunk(here("scripts", "02preprocess.R"))
knitr::read_chunk(here("scripts", "03svm-radial-hyper.R"))
knitr::read_chunk(here("scripts", "03linear-model.R"))
```

# Preparation

```{r preparation, child = here("documents", "preparation.Rmd")}
```

# Fit with Profession

```{r recipe-with-profession}
```

```{r svm-radial}
```

```{r linear-model}
```

```{r}
fits <- as.data.frame(cbind(summary(data_cv$r2_svmr),
                            summary(data_cv$r2_lm), summary(data_cv$rmse_svmr),
                            summary(data_cv$rmse_lm)))
names(fits) <- c("R2 SVMR", "R2 Linear Model", "RMSE SVMR", "RMSE Linear Model")
pander(fits)
```

```{r}
ggplot(data_cv, aes(rmse_svmr)) + geom_density() + theme_minimal()
ggplot(data_cv, aes(id, rmse_svmr)) + geom_boxplot() + theme_minimal()

ggplot(data_cv, aes(r2_svmr)) + geom_density() + theme_minimal()
ggplot(data_cv, aes(id, r2_svmr)) + geom_boxplot() + theme_minimal()

ggplot(data_cv, aes(rmse_lm)) + geom_density() + theme_minimal()
ggplot(data_cv, aes(id, rmse_svmr)) + geom_boxplot() + theme_minimal()

ggplot(data_cv, aes(r2_lm)) + geom_density() + theme_minimal()
ggplot(data_cv, aes(id, r2_lm)) + geom_boxplot() + theme_minimal()
```

```{r}
data_cv_with <- data_cv
```

# Fit without Profession

```{r recipe-without-profession}
```

```{r svm-radial}
```

```{r linear-model}
```

```{r}
fits <- as.data.frame(cbind(summary(data_cv$r2_svmr),
                            summary(data_cv$r2_lm), summary(data_cv$rmse_svmr),
                            summary(data_cv$rmse_lm)))
names(fits) <- c("R2 SVMR", "R2 Linear Model", "RMSE SVMR", "RMSE Linear Model")
pander(fits)
```

```{r}
ggplot(data_cv, aes(rmse_svmr)) + geom_density() + theme_minimal()
ggplot(data_cv, aes(id, rmse_svmr)) + geom_boxplot() + theme_minimal()

ggplot(data_cv, aes(r2_svmr)) + geom_density() + theme_minimal()
ggplot(data_cv, aes(id, r2_svmr)) + geom_boxplot() + theme_minimal()

ggplot(data_cv, aes(rmse_lm)) + geom_density() + theme_minimal()
ggplot(data_cv, aes(id, rmse_svmr)) + geom_boxplot() + theme_minimal()

ggplot(data_cv, aes(r2_lm)) + geom_density() + theme_minimal()
ggplot(data_cv, aes(id, r2_lm)) + geom_boxplot() + theme_minimal()
```